### ISSUE TITLE
Finalize Airtime > Libretime forking

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1378]
I haven't found any issue with regards to rebranding from Airtime to Libretime.

This is a global ticket which will attempt to gather all the steps required to rebrand the project to Libretime and remove most of the airtime occurrences in the code.

This will be considered as a breaking change and should be resolved before we hit v3 beta. Leaving some airtime migration steps for the future will probably only cause trouble and headache, we should do it once and for all.

While we rename the files and dirs:
- We should remove useless Libretime/Airtime names in the code (eg `AirtimeApiClient` > `ApiClient`)
- We might alter some of the paths and names for homogeneous and simpler paths (eg `pypo` > `playout`).
- We should consider using symlinks to deploy configurations across the system (eg `/etc/libretime/apache.conf => /etc/apache2/site-enabled/libretime.conf`).
- We will try to follow the modern https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html as a non packaged software.

Some files should remain untouched:
- LEGACY.md

What need to be done:
- [x] Rename `airtime_mvc` to `legacy` (having airtime_mvc in most of the paths will probably make any search and replace difficult) #1379 
- [x] Rename the python packages (=> `libretime-*`) #1373
- [x] Rename the entrypoints/scripts/binaries (=> `libretime-*`) #1373
- [x] Rename the services  (=> `libretime-*.service`)
- [ ] Rename the config paths (=> `/etc/libretime/config.yml`) #420 
- [x] Rename the runtime paths #1380 
- [x] Rename the logs paths  (=> `/var/log/libretime/*`)
- [ ] Rename the shared files paths (=> `/usr/share/libretime/legacy`)

**Comment by paddatrapper** [comment]
Eventually it would be nice to have them as environment variables because it makes things like contanerization easier. Whether it is worth it now is probably up for a cost/benefit analysis

**Comment by jooola** [comment]
In the process of renaming a lot of paths, I wanted to propose less fixed paths.

Currently many paths a hardcoded in the code, and this isn't helping us at all. I see at least 4 different setup:
- dev/testing:  I expect the logs to go in the working directory.
- docker: I would simply log to stderr and leave other tools get the logs.
- packaged setup: In a packaged setup, I expect the files to be deployed the well known `/etc` `/var/log` `/var/tmp` paths.
- custom production setup: one might want to install libretime with custom paths.
- 
So I propose to leave the package/images maintainers handle there own path, and make the code always use dev/testing paths.

**Comment by paddatrapper** [comment]
- Dev/testing could even write to stdout running in a console. Though not sure how that will work with our current setup. Writing to the working directory is also complicated with lots of moving parts. I.e. in vagrant what is defined as the working directory? The project root /vagrant, the application root, some subdirectory?
- Docker should log to stdout, not stderr, but I agree that we shouldn't be managing those logs
- Packages - correct

For the moment, the majority of people install LibreTime using the install script. That should use the package file paths, but accept flags to change them.

**Comment by jooola** [comment]
Yes, dev/testing could log to the console, agreed.

Vagrant would be a custom production setup ? With most of the path similar to the packaged one.

Behind all this, the idea is to let external tool (docker/systemd) handle most of the system integration. As we should not bother about it. This mean that we could even let systemd handle the logging (journald), and let the app log to the console as well.

In addition, I would extend our use of systemd and use the [WorkingDirectory](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=) parameter to define a working dir for the app, and apart from logs (? as said above, could be ignored) and the /tmp dir, the app should only have to create files in the that working dir.

As example I would see:
- `/var/libretime/playout/` <- Working Directory for playout
- `/tmp/libretime/playout` <- this is actually useless, should be handled with [python tmp dir](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory)
- `/var/log/libretime/playout`

**Comment by paddatrapper** [comment]
Sounds good. The only change I would make is put things under `/var/lib/libretime/` instead of `/var/libretime`. Following the Filesystem Hierarchy Standard - https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html

I'm tempted by letting systemd handle logging, but I think it will make getting logs from people to debug issues tricky.
